Issue 2 view entries
hnguy96/code-journal pull request #6
Opened 2021-03-31 17:52 UTC by hnguy96

![Screen Shot 2021-03-31 at 10 49 09 AM](https://user-images.githubusercontent.com/59902729/113188586-14704980-920f-11eb-927c-343e08af6a5c.png)
![Screen Shot 2021-03-31 at 10 49 35 AM](https://user-images.githubusercontent.com/59902729/113188598-1803d080-920f-11eb-8835-cece74018e3f.png)

2021-03-31 17:56 UTC, codingcodymiller requested changes

2021-03-31 17:56 UTC, codingcodymiller commented on js/main.js
>    $form.reset();
You should be adding the newly submitted entry to the list of entries here, too. You are currently only making DOM trees for new elements when the page loads, but you also need to generate one for each new entry and add it to the DOM.

2021-04-01 18:10 UTC, hnguy96 commented
![Screen Shot 2021-04-01 at 11 09 31 AM](https://user-images.githubusercontent.com/59902729/113336138-c759a980-92da-11eb-9547-291a2c8414c2.png)
![Screen Shot 2021-04-01 at 11 09 35 AM](https://user-images.githubusercontent.com/59902729/113336141-c9236d00-92da-11eb-80c1-755ad3500e9d.png)

2021-04-01 18:14 UTC, codingcodymiller requested changes

2021-04-01 18:14 UTC, codingcodymiller commented on js/main.js
> +    var dataView = event.target.getAttribute('data-view');
You are still using `event` in here, even though you are not using this as an event handler in your submit function. You should create a function that has a `view` parameter that is meant to be the name of the view to switch to as a string, so you can call that function and pass in the view name from `data-view` as an argument.

2021-04-01 18:14 UTC, codingcodymiller commented on css/styles.css
> +}
There is already a rule for the `hidden` class in `layout.css`, this can be removed.

2021-04-01 22:07 UTC, codingcodymiller requested changes

2021-04-01 22:07 UTC, codingcodymiller commented on js/main.js
> +  getDataValue('entries');
This should just be `changeView("entries")`

2021-04-01 22:07 UTC, codingcodymiller commented on js/main.js
> +  getDataValue('entries');
`getDataValue` is a event handler function, and there is no event here.

2021-04-01 22:07 UTC, codingcodymiller commented on js/main.js
> +function getDataValue(view) {
No `view` parameter needed here.

2021-04-01 22:26 UTC, hnguy96 commented
![Screen Shot 2021-04-01 at 3 19 47 PM](https://user-images.githubusercontent.com/59902729/113360145-106f2500-92fe-11eb-9dd8-0b0ec744391f.png)
![Screen Shot 2021-04-01 at 3 19 54 PM](https://user-images.githubusercontent.com/59902729/113360141-0d743480-92fe-11eb-8dff-0e3e81dc9be7.png)

2021-04-02 00:48 UTC, hnguy96 commented
![Screen Shot 2021-04-01 at 5 47 24 PM](https://user-images.githubusercontent.com/59902729/113368018-75cd1100-9312-11eb-9558-9e0905831fe2.png)
![Screen Shot 2021-04-01 at 5 47 20 PM](https://user-images.githubusercontent.com/59902729/113368020-7796d480-9312-11eb-9b50-877b2b890600.png)

2021-04-03 00:28 UTC, codingcodymiller approved these changes

2021-04-03 19:27 UTC, merged